api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    swagger:
        versions: [3]
